<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>sprosi-api-7c2a1e4b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sprosi.Application\Sprosi.Application.csproj" />
    <ProjectReference Include="..\Sprosi.Data\Sprosi.Data.csproj" />
    <ProjectReference Include="..\Sprosi.Infrastructure\Sprosi.Infrastructure.csproj" />
  </ItemGroup>

</Project>
